/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include<stdio.h>
/* Header for class com_example_dell_peddet_Opencv */
#include "opencv2/opencv.hpp"
using namespace cv;
using namespace std;
#ifndef _Included_com_example_dell_peddet_Opencv
#define _Included_com_example_dell_peddet_Opencv
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_dell_peddet_Opencv
 * Method:    pedDetection
 * Signature: (J)V
 */
void detect(Mat& frame);
JNIEXPORT void JNICALL Java_com_example_dell_peddet_Opencv_pedDetection
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
